### ISSUE TITLE
Bad Resource ID

### ISSUE THREAD

**Issue by balzaczyy** [joakimunge/denoliver#15]
Please check this error:
BadResource: Bad resource ID
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async handleWs (https://deno.land/x/denoliver/mod.ts:84:22)
    at async router (https://deno.land/x/denoliver/mod.ts:104:12)

index.html
<!DOCTYPE html>
<body>
<div id="root"></div>
<script type="module" src="js/app.js"></script>
</body>
</html>

js/app.js
import { Button } from 'https://cdn.pika.dev/antd@^4.3.1';
import React from 'https://cdn.pika.dev/react@^16.13.1'
import ReactDOM from 'https://cdn.pika.dev/react-dom@^16.13.1';

const e = React.createElement;

class LikeButton extends React.Component {
  constructor(props) {
    super(props);
    this.state = { liked: false };
  }

  render() {
    if (this.state.liked) {
      return 'You liked this.';
    }

    return e(
      'button',
      { onClick: () => this.setState({ liked: true }) },
      'Like'
    );
  }
}

const root = document.querySelector('#root');
ReactDOM.render(e(LikeButton), root);

**Comment by joakimunge** [comment]
Hi, thanks for the report. I will look into it, but I think it should be resolved with v2.0.0 that is in the pipe

**Comment by joakimunge** [comment]
@balzaczyy This should now be resolved with #6 

Please feel free to reopen if you encounter it again
