### ISSUE TITLE
Uncaught Error: Broken Pipe

### ISSUE THREAD

**Issue by joakimunge** [joakimunge/denoliver#28]
Broken Pipe error randomly appears. Seems to be an issue with the response not being awaited in some cases.

![image](https://user-images.githubusercontent.com/24225542/92102780-56532180-eddf-11ea-83d8-120d93bf0c81.png)

**Comment by dkolba** [comment]
Still getting `ERROR: Broken pipe (os error 32)` after several (5-7) websocket reloads on macOS.
