### ISSUE TITLE
Install broken with deno 1.16.1

### ISSUE THREAD

**Issue by dkolba** [joakimunge/denoliver#41]
I am getting the error
```
Check https://deno.land/x/denoliver/mod.ts
error: TS2339 [ERROR]: Property 'getIterator' does not exist on type 'ReadableStream<R>'.
  return res.readable.getIterator();
                      ~~~~~~~~~~~
    at https://deno.land/std@0.81.0/async/pool.ts:45:23
```
upon install with deno 1.16.1

**Comment by joakimunge** [comment]
Hey. Thanks for reporting this. I will have a look during the week.

**Comment by joakimunge** [comment]
Hi, I have merged a fix for installing this on later versions of Deno `>1.16`. I will push a new release shortly!

It looks like Deno has implemented native HTTP support now, so I am planning to release a major version. If you want to partake or discuss the new major version, please do so here:

https://github.com/joakimunge/denoliver/issues/43
